### ISSUE TITLE
Website Checklist

### ISSUE THREAD

**Issue by pramslam** [pramslam/IndieGameCon#17]
Template:
https://eugtech.github.io/OpenEugeneFestivalWeb/

- [x] Home - Who, What, Where, When? Buy tickets here, Code of Conduct
- [x] Games - Submit Game (form), List of submitted games, List of submitted developers
- [x] Programs - List of Programs and Presenters
- [x] Schedule - Day, Time, What
- [x] Sponsors - Title Sponsor, Presenting Sponsors, Supporting Sponsors, Community Sponsors
- [x] Media - Articles, Blog posts, and media links
- [x] About - Who we are, and Leadership Team with images

**Comment by mckelveygreg** [comment]
Lets make issues for each page, and then once content is there, we'll add it to the site.

**Comment by pramslam** [comment]
Home - Who, What, Where, When? Buy tickets here, Code of Conduct

**Comment by andy-dandy** [comment]
Do we need a separate FAQ page? A lot of the questions in the FAQ area on the current site will be answered on their own respective pages in the updated site. @mckelveygreg

**Comment by pramslam** [comment]
@mckelveygreg Here is a slightly more organized version of the content I'd like on the website.
https://github.com/pramslam/IndieGameCon/blob/master/docs/website.md

**Comment by pramslam** [comment]
Most of this is done, needs some better content, but we can move forward
