### ISSUE TITLE
Sponsor Contact Checklist

### ISSUE THREAD

**Issue by andy-dandy** [pramslam/IndieGameCon#19]
## Sponsor Checklist

- [ ] Glimmer Technology
- [ ] Travel Lane County
- [ ] Intel
- [ ] Lane Community College
- [ ] RAIN Eugene
- [ ] Oregon Story Board
- [ ] Holiday Inn Express
- [ ] Oregon Video Game Association
- [ ] Oregon Film
- [ ] Portland Indie Game Squad (PIG)
- [ ] Pixel Arts Game Education

### Glimmer Technology

http://www.glimmer.tech/

Injects animation and sound into the world, as seen through a mobile phone camera Relies on special images to trigger content Requires a free app, Glimmer XP, that is available on Apple and Android phones Combines traditional art forms and next-generation technology

- [ ] Contacted
      -Which organizer has been in contact?
      -Who did they contact?
      -How?
- [ ] Scheduled first meetup
      -When? 
      -Who is meeting with them?
      -Important info from meeting
- [ ] Follow up email and/or phone call
      -Any new info from this conversation?
- [ ] Scheduled second meeting (if necessary)
      -When?
      -Who is meeting with them?
- [ ] Committed to sponsorship level
      -Which level?
      -When do we receive money?
- [ ] Given them the info they need to give us money

#

### Travel Lane County

https://www.eugenecascadescoast.org/members/about-us/

Notes: They have sponsored us in 2014 and 2015.

Contacts: Juanita Metzler Convention Sales Manager Phone: 541.743.8758 Email: Juanita@EugeneCascadesCoast.org

Linda Norris Convention Services Manager Phone: 541.743.8756 Email: Linda@EugeneCascadesCoast.org

- [ ] Contacted
      -Which organizer has been in contact?
      -Who did they contact?
      -How?
- [ ] Scheduled first meetup
      -When? 
      -Who is meeting with them?
      -Important info from meeting
- [ ] Follow up email and/or phone call
      -Any new info from this conversation?
- [ ] Scheduled second meeting (if necessary)
      -When?
      -Who is meeting with them?
- [ ] Committed to sponsorship level
      -Which level?
      -When do we receive money?
- [ ] Given them the info they need to give us money

#

### Intel

https://www.intel.com/content/www/us/en/corporate-responsibility/intel-in-oregon.html

Notes: Has sponsored us in 2014.

Contacts: Customers who need to contact Intel headquarters can call 1-408-765-8080 to reach the operator. You will need to know the office you need to contact to help the operator direct your call. If you have no idea what department you need, explain your issue to the operator to help direct the call. https://www.intel.com/content/www/us/en/forms/corporate/corporate-questions-contact-us.html

- [ ] Contacted
      -Which organizer has been in contact?
      -Who did they contact?
      -How?
- [ ] Scheduled first meetup
      -When? 
      -Who is meeting with them?
      -Important info from meeting
- [ ] Follow up email and/or phone call
      -Any new info from this conversation?
- [ ] Scheduled second meeting (if necessary)
      -When?
      -Who is meeting with them?
- [ ] Committed to sponsorship level
      -Which level?
      -When do we receive money?
- [ ] Given them the info they need to give us money

#

### Lane Community College (Game Development)

https://www.lanecc.edu/cit/simulation-and-game-development

Notes: They have sponsored us in 2014.

Contacts: Andy will know more info!

- [ ] Contacted
      -Which organizer has been in contact?
      -Who did they contact?
      -How?
- [ ] Scheduled first meetup
      -When? 
      -Who is meeting with them?
      -Important info from meeting
- [ ] Follow up email and/or phone call
      -Any new info from this conversation?
- [ ] Scheduled second meeting (if necessary)
      -When?
      -Who is meeting with them?
- [ ] Committed to sponsorship level
      -Which level?
      -When do we receive money?
- [ ] Given them the info they need to give us money
# 

### RAIN EUGENE

http://www.raineugene.org/

Notes: They have sponsored us in 2014.

Contacts: None, Joe Marushak stopped working there.

- [ ] Contacted
      -Which organizer has been in contact?
      -Who did they contact?
      -How?
- [ ] Scheduled first meetup
      -When? 
      -Who is meeting with them?
      -Important info from meeting
- [ ] Follow up email and/or phone call
      -Any new info from this conversation?
- [ ] Scheduled second meeting (if necessary)
      -When?
      -Who is meeting with them?
- [ ] Committed to sponsorship level
      -Which level?
      -When do we receive money?
- [ ] Given them the info they need to give us money
#

### Oregon Story Board

http://www.oregonstoryboard.org/

Notes: They have sponsored us in 2014.

Contacts: info@oregonstoryboard.org

- [ ] Contacted
      -Which organizer has been in contact?
      -Who did they contact?
      -How?
- [ ] Scheduled first meetup
      -When? 
      -Who is meeting with them?
      -Important info from meeting
- [ ] Follow up email and/or phone call
      -Any new info from this conversation?
- [ ] Scheduled second meeting (if necessary)
      -When?
      -Who is meeting with them?
- [ ] Committed to sponsorship level
      -Which level?
      -When do we receive money?
- [ ] Given them the info they need to give us money
# 

### Holiday Inn Express

https://www.ihg.com/holidayinnexpress/hotels/us/en/springfield/sfieu/hoteldetail

Notes: They have sponsored us in 2014. We may have gotten this sponsorship for keynote speaker hotel rooms.

Contacts: (541) 342-1243

- [ ] Contacted
      -Which organizer has been in contact?
      -Who did they contact?
      -How?
- [ ] Scheduled first meetup
      -When? 
      -Who is meeting with them?
      -Important info from meeting
- [ ] Follow up email and/or phone call
      -Any new info from this conversation?
- [ ] Scheduled second meeting (if necessary)
      -When?
      -Who is meeting with them?
- [ ] Committed to sponsorship level
      -Which level?
      -When do we receive money?
- [ ] Given them the info they need to give us money
#

### Oregon Video Game Association

https://www.oregongames.org/

Notes: They have sponsored us in 2015.

Contacts: Website lists Will Lewis as a writer but there is no contact email.

- [ ] Contacted
      -Which organizer has been in contact?
      -Who did they contact?
      -How?
- [ ] Scheduled first meetup
      -When? 
      -Who is meeting with them?
      -Important info from meeting
- [ ] Follow up email and/or phone call
      -Any new info from this conversation?
- [ ] Scheduled second meeting (if necessary)
      -When?
      -Who is meeting with them?
- [ ] Committed to sponsorship level
      -Which level?
      -When do we receive money?
- [ ] Given them the info they need to give us money
#

### Oregon Film

https://oregonfilm.org/

Notes: They have sponsored us in 2015.

Contacts: Our office hours are generally 9am to 5pm (Monday-Friday). Please call to make an appt. (971) 254-4020

- [ ] Contacted
      -Which organizer has been in contact?
      -Who did they contact?
      -How?
- [ ] Scheduled first meetup
      -When? 
      -Who is meeting with them?
      -Important info from meeting
- [ ] Follow up email and/or phone call
      -Any new info from this conversation?
- [ ] Scheduled second meeting (if necessary)
      -When?
      -Who is meeting with them?
- [ ] Committed to sponsorship level
      -Which level?
      -When do we receive money?
- [ ] Given them the info they need to give us money
#

### Portland Indie Game Squad

https://pigsquad.com/

Notes: They have sponsored us in 2015. This may be a great source for game contributors.

Contacts: info@pigsquad.com

- [ ] Contacted
      -Which organizer has been in contact?
      -Who did they contact?
      -How?
- [ ] Scheduled first meetup
      -When? 
      -Who is meeting with them?
      -Important info from meeting
- [ ] Follow up email and/or phone call
      -Any new info from this conversation?
- [ ] Scheduled second meeting (if necessary)
      -When?
      -Who is meeting with them?
- [ ] Committed to sponsorship level
      -Which level?
      -When do we receive money?
- [ ] Given them the info they need to give us money
#
### Pixel Arts Game Education

https://www.gameeducationpdx.com/

Notes: They have sponsored us in 2015.

Contacts: https://www.gameeducationpdx.com/contact/

- [ ] Contacted 
      - Which organizer has been in contact?
      - Who did they contact?
      - How?
- [ ] Scheduled first meetup
      - When? 
      - Who is meeting with them?
      - Important info from meeting
- [ ] Follow up email and/or phone call
      -Any new info from this conversation?
- [ ] Scheduled second meeting (if necessary)
      -When?
      -Who is meeting with them?
- [ ] Committed to sponsorship level
      -Which level?
      -When do we receive money?
- [ ] Given them the info they need to give us money

**Comment by pramslam** [comment]
Let's make each sponsor it's own issue and change this issue's main text to a checklist of all the sponsors.
