### ISSUE TITLE
Catering Contact Checklist

### ISSUE THREAD

**Issue by andy-dandy** [pramslam/IndieGameCon#20]
### Name

Website (clickable link)

Did they cater for us or a local tech event before?
Alcohol? Food? Both?

- [ ] Contacted
      -Who made first contact?
      -Who did you contact?
      -How?
- [ ] Scheduled first meetup
      -When? 
      -Who is meeting with them?
      -Important info from meeting
- [ ] Follow up email and/or phone call
      -Any new info from this conversation?
- [ ] Scheduled second meeting (if necessary)
      -When?
      -Who is meeting with them?
#### **What is their cost and which days/times can they cater?**
#

### Laughing Planet
